# Github actions pipline that deploys app in ./public/ to google cloud platform cloud functions

name: Deploy to Cloud Functions

on:
  push:
    branches:
      - test

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy to Cloud Functions
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          credentials: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          name: "index"
          source: ./public/