# A github actions pipeline that deploys and runs app.js on google cloud functions

# This pipeline uses the [Google Cloud Functions](https://cloud.google.com/functions) action to deploy and run the app.js function on google cloud functions.

## Prerequisites

# * A [GCP project](https://cloud.google.com/resource-manager/docs/creating-managing-projects) with the [Cloud Functions API](https://console.cloud.google.com/apis/library/cloudfunctions.googleapis.com) enabled.
# * A [GCP service account](https://cloud.google.com/iam/docs/creating-managing-service-accounts) with the `Cloud Functions Developer` role.
# * A [GCP service account key](https://cloud.google.com/iam/docs/creating-managing-service-account-keys) for the service account.
# * A [GCP storage bucket](https://cloud.google.com/storage/docs/creating-buckets) to store the deployment package.

## Secrets

# This pipeline requires the following secrets:

# * `GCP_PROJECT_ID`: The ID of your GCP project.
# * `GCP_SA_KEY`: The JSON key for your service account.

## Usage

# To use this pipeline, create a `.github/workflows/main.yml` file with the following contents:

name: Deploy to GCP

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: google-github-actions/setup-gcloud@main
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true
      - uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: my-cloud-function
          runtime: nodejs12
          entry_point: app
          source_dir: .
          trigger_http: true
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          bucket: my-deployment-bucket
          credentials: ${{ secrets.GCP_SA_KEY }}

## Arguments

# For details on the arguments this action supports, see [Deploy Cloud Functions](
