# Github actions pipline that deploys app in ./public/ to google cloud platform cloud functions

name: Deploy to Google Cloud Functions

on:
  push:
    branches:
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
            credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v0.5.1
        with:
            project_id: ${{ secrets.GCP_PROJECT_ID }}
            export_default_credentials: true

      - name: Deploy to Google Cloud Functions
        run: |
          gcloud functions deploy weatherApp \
            --runtime=nodejs14 \
            --trigger-http \
            --allow-unauthenticated \
            --source=./path/to/your/function/code
